FROM alpine:latest
LABEL org.opencontainers.image.authors="Sergey Safarov <s.safarov@gmail.com>"
RUN apk --no-cache upgrade
ADD kamailio_min-without_os_files.tar.gz /

ENTRYPOINT ["kamailio", "-DD", "-E"]
