#!/bin/bash

IMAGE_NAME="${IMAGE_NAME:-kamailio:master}"

init_local_repo() {
    docker network create kamailio-build
    docker run \
           --detach \
           --network kamailio-build \
           --name local-repo \
           --hostname local-repo \
           --rm=true \
           --volume=`pwd`/apk_files:/usr/share/nginx/html:ro \
           nginx
}

build_images() {
    docker build --no-cache -t $IMAGE_NAME .
    docker build --no-cache -t $IMAGE_NAME-alpine -f Dockerfile.alpine .
    docker build --no-cache -t $IMAGE_NAME-alpine.debug --network kamailio-build -f Dockerfile.debug .
}

build_cleanup() {
    docker stop local-repo
    docker network rm kamailio-build
    rm -Rf apk_files kamailio_img.tar.gz kamailio_min-without_os_files.tar.gz
}

set -x
set -e

init_local_repo
build_images
build_cleanup
exit 0
