#!/bin/bash -e

set -o errexit -o nounset -o pipefail
set -x
# Setting environment vars
ALPINE_BRANCH="${ALPINE_BRANCH:-latest}"
DOCKER_REPO="${DOCKER_REPO:-kamailio/kamailio-ci}"

if [ "$SOURCE_BRANCH" = "master" ];then
    ALPINE_BRANCH="edge"
fi

refresh_builder() {
    docker pull alpine:${ALPINE_BRANCH} || true
    docker pull ${DOCKER_REPO}:builder-alpine.${ALPINE_BRANCH} || true
    local SHA_ALPINE=$(docker image inspect -f '{{index .RootFS.Layers 0}}' alpine:${ALPINE_BRANCH})
    local SHA_BUILDER=$(docker image inspect -f '{{index .RootFS.Layers 0}}' ${DOCKER_REPO}:builder-alpine.${ALPINE_BRANCH})
    if [ "${SHA_ALPINE}" = "${SHA_BUILDER}" ]; then
      echo "Builder already use fresh alpine base image. Continue"
      return 0
    fi
    sed -i -e "s/alpine:latest/alpine:${ALPINE_BRANCH}/" Dockerfile.builder
    docker build -t ${DOCKER_REPO}:builder-alpine.${ALPINE_BRANCH} --file Dockerfile.builder .
    if [ "${GITHUB_REPOSITORY_OWNER}" == "kamailio" ]; then
      docker push ${DOCKER_REPO}:builder-alpine.${ALPINE_BRANCH}
    fi
}

echo "=> Refreshing builder image"
refresh_builder

echo "=> Build Kamailio source code"

if [ "${ALPINE_BRANCH}" = "edge" ]; then
    sed -i -e 's/latest$/edge/' Dockerfile.alpine
    sed -i -e 's/latest$/edge/' Dockerfile.debug
fi

docker run --volume=`pwd`/../../..:/usr/src/kamailio \
           --volume=`pwd`/build.sh:/build.sh \
           --entrypoint=/build.sh \
           ${DOCKER_REPO}:builder-alpine.${ALPINE_BRANCH}

exit $?
