---
name: alpine docker builder image
on:
  push:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_NAME: kamailio-ci
  SOURCE_BRANCH: ${{ github.ref_name }}
  DOCKER_REPO: ghcr.io/kamailio/kamailio-ci
  REFRESH_ONLY: true

jobs:
  x86_64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: print latest_commit
      run: echo ${{ github.sha }}

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        since_last_remote_commit: true

    - name: Dockerfile.builder
      id: changed-files-builder
      uses: tj-actions/changed-files@v45
      with:
        files: alpine/Dockerfile.builder

    - name: Login to GitHub Container Registry
      if: steps.changed-files-builder.outputs.any_changed == 'true'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: generate builder
      if: steps.changed-files-builder.outputs.any_changed == 'true'
      run: |
        cd alpine
        ./hooks/pre_build
